
import { musicImages, movieImages, bookImages, tvShowImages } from './images';

// Mock chart data for different content types
export const getMovieChartData = () => [
  {
    id: "item1",
    rank: 1,
    previousRank: 2,
    title: "The Shawshank Redemption",
    type: "movie",
    imageUrl: movieImages[0],
    score: 98,
    collections: 842,
  },
  {
    id: "item12",
    rank: 2,
    previousRank: 1,
    title: "Inception",
    type: "movie",
    imageUrl: movieImages[4],
    score: 95,
    collections: 756,
  },
  {
    id: "item2",
    rank: 3,
    previousRank: 9,
    title: "The Godfather",
    type: "movie",
    imageUrl: movieImages[1],
    score: 93,
    collections: 715,
  },
  {
    id: "item31",
    rank: 4,
    previousRank: 7,
    title: "The Shining",
    type: "movie",
    imageUrl: horrorMovieImages[0],
    score: 91,
    collections: 687,
  },
  {
    id: "item32",
    rank: 5,
    previousRank: 3,
    title: "Pulp Fiction",
    type: "movie",
    imageUrl: movieImages[1],
    score: 90,
    collections: 650,
  },
  {
    id: "item33",
    rank: 6,
    previousRank: 8,
    title: "The Dark Knight",
    type: "movie",
    imageUrl: horrorMovieImages[2],
    score: 89,
    collections: 635,
  },
  {
    id: "item34",
    rank: 7,
    previousRank: 6,
    title: "Interstellar",
    type: "movie",
    imageUrl: movieImages[5],
    score: 87,
    collections: 610,
  },
  {
    id: "item35",
    rank: 8,
    previousRank: 11,
    title: "The Matrix",
    type: "movie",
    imageUrl: movieImages[3],
    score: 86,
    collections: 590,
  },
  {
    id: "item36",
    rank: 9,
    previousRank: 10,
    title: "Parasite",
    type: "movie",
    imageUrl: movieImages[7],
    score: 85,
    collections: 575,
  },
  {
    id: "item37",
    rank: 10,
    previousRank: 13,
    title: "Fight Club",
    type: "movie",
    imageUrl: movieImages[2],
    score: 84,
    collections: 552,
  },
];

export const getMusicChartData = () => [
  {
    id: "item21",
    rank: 1,
    previousRank: 3,
    title: "Bohemian Rhapsody",
    type: "music",
    imageUrl: musicImages[0],
    score: 97,
    collections: 801,
  },
  {
    id: "item23",
    rank: 2,
    previousRank: 1,
    title: "Hotel California",
    type: "music",
    imageUrl: musicImages[2],
    score: 94,
    collections: 754,
  },
  {
    id: "item22",
    rank: 3,
    previousRank: 2,
    title: "Stairway to Heaven",
    type: "music",
    imageUrl: musicImages[1],
    score: 92,
    collections: 721,
  },
  {
    id: "item24",
    rank: 4,
    previousRank: 5,
    title: "Imagine",
    type: "music",
    imageUrl: musicImages[3],
    score: 90,
    collections: 680,
  },
  {
    id: "item25",
    rank: 5,
    previousRank: 4,
    title: "Billie Jean",
    type: "music",
    imageUrl: musicImages[4],
    score: 89,
    collections: 645,
  },
  {
    id: "item26",
    rank: 6,
    previousRank: 8,
    title: "Hey Jude",
    type: "music",
    imageUrl: musicImages[5],
    score: 88,
    collections: 632,
  },
  {
    id: "item27",
    rank: 7,
    previousRank: 6,
    title: "Like a Rolling Stone",
    type: "music",
    imageUrl: musicImages[6],
    score: 86,
    collections: 590,
  },
  {
    id: "item28",
    rank: 8,
    previousRank: 9,
    title: "Purple Haze",
    type: "music",
    imageUrl: musicImages[7],
    score: 84,
    collections: 570,
  },
  {
    id: "item29",
    rank: 9,
    previousRank: 12,
    title: "Smells Like Teen Spirit",
    type: "music",
    imageUrl: musicImages[8],
    score: 83,
    collections: 550,
  },
  {
    id: "item30",
    rank: 10,
    previousRank: 7,
    title: "Superstition",
    type: "music",
    imageUrl: musicImages[9],
    score: 82,
    collections: 530,
  },
];

export const getBookChartData = () => [
  {
    id: "item11",
    rank: 1,
    previousRank: 2,
    title: "Sapiens: A Brief History of Humankind",
    type: "book",
    imageUrl: bookImages[0],
    score: 96,
    collections: 789,
  },
  {
    id: "item13",
    rank: 2,
    previousRank: 1,
    title: "To Kill a Mockingbird",
    type: "book",
    imageUrl: bookImages[1],
    score: 93,
    collections: 743,
  },
  {
    id: "item14",
    rank: 3,
    previousRank: 5,
    title: "1984",
    type: "book",
    imageUrl: bookImages[2],
    score: 92,
    collections: 712,
  },
  {
    id: "item15",
    rank: 4,
    previousRank: 3,
    title: "Harry Potter and the Sorcerer's Stone",
    type: "book",
    imageUrl: bookImages[3],
    score: 90,
    collections: 675,
  },
  {
    id: "item16",
    rank: 5,
    previousRank: 4,
    title: "The Lord of the Rings",
    type: "book",
    imageUrl: bookImages[4],
    score: 89,
    collections: 642,
  },
  {
    id: "item17",
    rank: 6,
    previousRank: 8,
    title: "The Great Gatsby",
    type: "book",
    imageUrl: bookImages[5],
    score: 88,
    collections: 621,
  },
  {
    id: "item18",
    rank: 7,
    previousRank: 9,
    title: "Pride and Prejudice",
    type: "book",
    imageUrl: bookImages[6],
    score: 86,
    collections: 595,
  },
  {
    id: "item19",
    rank: 8,
    previousRank: 6,
    title: "The Alchemist",
    type: "book",
    imageUrl: bookImages[7],
    score: 84,
    collections: 570,
  },
  {
    id: "item20",
    rank: 9,
    previousRank: 7,
    title: "The Catcher in the Rye",
    type: "book",
    imageUrl: bookImages[8],
    score: 83,
    collections: 540,
  },
  {
    id: "item41",
    rank: 10,
    previousRank: 11,
    title: "Brave New World",
    type: "book",
    imageUrl: bookImages[9],
    score: 82,
    collections: 525,
  },
];

export const getTvShowChartData = () => [
  {
    id: "item51",
    rank: 1,
    previousRank: 3,
    title: "Breaking Bad",
    type: "tvshow",
    imageUrl: tvShowImages[0],
    score: 97,
    collections: 820,
  },
  {
    id: "item52",
    rank: 2,
    previousRank: 1,
    title: "Game of Thrones",
    type: "tvshow",
    imageUrl: tvShowImages[1],
    score: 94,
    collections: 760,
  },
  {
    id: "item53",
    rank: 3,
    previousRank: 2,
    title: "The Wire",
    type: "tvshow",
    imageUrl: tvShowImages[2],
    score: 93,
    collections: 730,
  },
  {
    id: "item54",
    rank: 4,
    previousRank: 5,
    title: "The Sopranos",
    type: "tvshow",
    imageUrl: tvShowImages[3],
    score: 91,
    collections: 695,
  },
  {
    id: "item55",
    rank: 5,
    previousRank: 4,
    title: "Stranger Things",
    type: "tvshow",
    imageUrl: tvShowImages[4],
    score: 89,
    collections: 650,
  },
  {
    id: "item56",
    rank: 6,
    previousRank: 8,
    title: "The Office",
    type: "tvshow",
    imageUrl: tvShowImages[0],
    score: 88,
    collections: 630,
  },
];
